package ar.edu.unlu.backgammon.modelo.enumerados;

public enum Estado_Tablero {
	MOVIMIENTO_VALIDO,
	MOVIMIENTO_INVALIDO,
	MOVIMIENTO_REALIZADO,
	MOVIMIENTO_REALIZADO_FIN_TURNO,
	TURNO_INCORRECTO,
	DADO_SIN_USOS,
	DADOS_TIRADOS,
	NO_ES_FICHA_MAS_CERCANA,
	FICHA_INCORRECTA,
	FICHAS_EN_OTROS_CUADRANTES,
	FICHA_SALE,
	FICHA_COMIDA,
	HAY_FICHAS_COMIDAS,
	USUARIO_CONECTADO,
	USUARIO_REPETIDO,
	PARTIDA_INICIADA, 
	PARTIDA_CONTINUA,
	PARTIDA_LLENA,
	PARTIDA_FINALIZADA_GANO_BLANCO,
	PARTIDA_FINALIZADA_GANO_NEGRO
}
